DROP TYPE LEVEL CASCADE;
DROP TABLE user_data CASCADE;
DROP TABLE caretaker CASCADE;
DROP TABLE help_group CASCADE;
DROP TABLE product CASCADE;
DROP TABLE needs CASCADE;
DROP TABLE donor CASCADE;
DROP TABLE donations CASCADE;
DROP TABLE person CASCADE;


